apt:
	build-essential
	python-pip
	python-yaml
	vim
pip:
	boto
	tornado
	gunicorn
.bashrc:
	export AWS_ACCESS_KEY_ID=<Key>
	export AWS_SECRET_ACCESS_KEY=<key>
	export PYTHONPATH=/path/to/repository/root
